version: '2'
services:
    node0:
        build: .
        # environment:
        ports:
            - 8080:8080

    node1:
        build: .
        # environment:
        ports:
            - 8081:8080

    node2:
        build: .
        # environment:
        ports:
            - 8082:8080